# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MIIL_PARAMETER_CREATER_GUI.ui'
#
# Created: Sat Mar 16 21:41:45 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 493)
        MainWindow.setMinimumSize(QtCore.QSize(951, 493))
        MainWindow.setMaximumSize(QtCore.QSize(951, 493))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 211, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_3.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton3.setGeometry(QtCore.QRect(110, 20, 93, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.pushButton3.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.pushButton3.setFont(font)
        self.pushButton3.setDefault(True)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2.setEnabled(True)
        self.pushButton2.setGeometry(QtCore.QRect(10, 20, 93, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButton2.setFont(font)
        self.pushButton2.setDefault(True)
        self.pushButton2.setObjectName("pushButton2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 931, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 150, 911, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_24.setFont(font)
        self.groupBox_24.setObjectName("groupBox_24")
        self.lineEdit4 = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit4.setEnabled(False)
        self.lineEdit4.setGeometry(QtCore.QRect(10, 20, 691, 20))
        self.lineEdit4.setObjectName("lineEdit4")
        self.pushButton5 = QtWidgets.QPushButton(self.groupBox_24)
        self.pushButton5.setGeometry(QtCore.QRect(810, 20, 93, 28))
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton21 = QtWidgets.QPushButton(self.groupBox_24)
        self.pushButton21.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton21.setFont(font)
        self.pushButton21.setAutoDefault(False)
        self.pushButton21.setDefault(False)
        self.pushButton21.setFlat(False)
        self.pushButton21.setObjectName("pushButton21")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 220, 911, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setObjectName("groupBox_21")
        self.lineEdit8 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit8.setEnabled(False)
        self.lineEdit8.setGeometry(QtCore.QRect(10, 20, 691, 20))
        self.lineEdit8.setObjectName("lineEdit8")
        self.pushButton10 = QtWidgets.QPushButton(self.groupBox_21)
        self.pushButton10.setGeometry(QtCore.QRect(810, 20, 93, 28))
        self.pushButton10.setObjectName("pushButton10")
        self.pushButton22 = QtWidgets.QPushButton(self.groupBox_21)
        self.pushButton22.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton22.setFont(font)
        self.pushButton22.setAutoDefault(False)
        self.pushButton22.setDefault(False)
        self.pushButton22.setFlat(False)
        self.pushButton22.setObjectName("pushButton22")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 290, 911, 61))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.lineEdit9 = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit9.setEnabled(False)
        self.lineEdit9.setGeometry(QtCore.QRect(10, 20, 591, 20))
        self.lineEdit9.setObjectName("lineEdit9")
        self.pushButton11 = QtWidgets.QPushButton(self.groupBox_23)
        self.pushButton11.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.pushButton11.setFont(font)
        self.pushButton11.setDefault(True)
        self.pushButton11.setObjectName("pushButton11")
        self.pushButton12 = QtWidgets.QPushButton(self.groupBox_23)
        self.pushButton12.setGeometry(QtCore.QRect(810, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.pushButton12.setFont(font)
        self.pushButton12.setDefault(True)
        self.pushButton12.setObjectName("pushButton12")
        self.pushButton23 = QtWidgets.QPushButton(self.groupBox_23)
        self.pushButton23.setGeometry(QtCore.QRect(610, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton23.setFont(font)
        self.pushButton23.setAutoDefault(False)
        self.pushButton23.setDefault(False)
        self.pushButton23.setFlat(False)
        self.pushButton23.setObjectName("pushButton23")
        self.groupBox_1 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 80, 911, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_1.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")
        self.lineEdit5 = QtWidgets.QLineEdit(self.groupBox_1)
        self.lineEdit5.setEnabled(False)
        self.lineEdit5.setGeometry(QtCore.QRect(10, 20, 691, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setObjectName("lineEdit5")
        self.pushButton6 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton6.setGeometry(QtCore.QRect(810, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton6.setFont(font)
        self.pushButton6.setAutoDefault(False)
        self.pushButton6.setDefault(False)
        self.pushButton6.setFlat(False)
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton19 = QtWidgets.QPushButton(self.groupBox_1)
        self.pushButton19.setGeometry(QtCore.QRect(710, 20, 93, 28))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton19.setFont(font)
        self.pushButton19.setAutoDefault(False)
        self.pushButton19.setDefault(False)
        self.pushButton19.setFlat(False)
        self.pushButton19.setObjectName("pushButton19")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 151, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBox4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox4.setGeometry(QtCore.QRect(10, 20, 131, 22))
        self.comboBox4.setObjectName("comboBox4")
        self.pushButton14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton14.setGeometry(QtCore.QRect(170, 20, 93, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton14.setFont(font)
        self.pushButton14.setObjectName("pushButton14")
        self.pushButton15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton15.setGeometry(QtCore.QRect(280, 20, 93, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton15.setFont(font)
        self.pushButton15.setObjectName("pushButton15")
        self.pushButton16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton16.setGeometry(QtCore.QRect(380, 20, 93, 51))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pushButton16.setFont(font)
        self.pushButton16.setObjectName("pushButton16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MIIL PARAMETER CREATER", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "STATE", None, -1))
        self.pushButton3.setText(QtWidgets.QApplication.translate("MainWindow", "SAVE SATE", None, -1))
        self.pushButton2.setText(QtWidgets.QApplication.translate("MainWindow", "LOAD STATE", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "CREATE PARAMETER FILE", None, -1))
        self.groupBox_24.setTitle(QtWidgets.QApplication.translate("MainWindow", "DATASET FOLDER", None, -1))
        self.pushButton5.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton21.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox_21.setTitle(QtWidgets.QApplication.translate("MainWindow", "WEIGHTS FOLDER", None, -1))
        self.pushButton10.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton22.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox_23.setTitle(QtWidgets.QApplication.translate("MainWindow", "PARAMETER FILE", None, -1))
        self.pushButton11.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton12.setText(QtWidgets.QApplication.translate("MainWindow", "SAVE", None, -1))
        self.pushButton23.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox_1.setTitle(QtWidgets.QApplication.translate("MainWindow", "LABEL FILE", None, -1))
        self.pushButton6.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton19.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "PERCENTAGE OF VALID", None, -1))
        self.pushButton14.setText(QtWidgets.QApplication.translate("MainWindow", "SHOW PRM", None, -1))
        self.pushButton15.setText(QtWidgets.QApplication.translate("MainWindow", "SHOW TRAIN", None, -1))
        self.pushButton16.setText(QtWidgets.QApplication.translate("MainWindow", "SHOW VALID", None, -1))

