# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MIIL_PARAMETER_CREATER_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(951, 493)
        MainWindow.setMinimumSize(QSize(951, 493))
        MainWindow.setMaximumSize(QSize(951, 493))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 211, 61))
        palette = QPalette()
        brush = QBrush(QColor(170, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.groupBox_3.setPalette(palette)
        font = QFont()
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.pushButton3 = QPushButton(self.groupBox_3)
        self.pushButton3.setObjectName(u"pushButton3")
        self.pushButton3.setGeometry(QRect(110, 20, 93, 31))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.pushButton3.setPalette(palette1)
        font1 = QFont()
        font1.setBold(True)
        font1.setUnderline(False)
        self.pushButton3.setFont(font1)
        self.pushButton2 = QPushButton(self.groupBox_3)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setEnabled(True)
        self.pushButton2.setGeometry(QRect(10, 20, 93, 31))
        self.pushButton2.setFont(font)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 80, 931, 361))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.groupBox_2.setPalette(palette2)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_24 = QGroupBox(self.groupBox_2)
        self.groupBox_24.setObjectName(u"groupBox_24")
        self.groupBox_24.setGeometry(QRect(10, 150, 911, 61))
        font2 = QFont()
        font2.setBold(False)
        self.groupBox_24.setFont(font2)
        self.lineEdit4 = QLineEdit(self.groupBox_24)
        self.lineEdit4.setObjectName(u"lineEdit4")
        self.lineEdit4.setEnabled(False)
        self.lineEdit4.setGeometry(QRect(10, 20, 691, 20))
        self.pushButton5 = QPushButton(self.groupBox_24)
        self.pushButton5.setObjectName(u"pushButton5")
        self.pushButton5.setGeometry(QRect(810, 20, 93, 28))
        self.pushButton21 = QPushButton(self.groupBox_24)
        self.pushButton21.setObjectName(u"pushButton21")
        self.pushButton21.setGeometry(QRect(710, 20, 93, 28))
        self.pushButton21.setFont(font2)
        self.pushButton21.setAutoDefault(False)
        self.pushButton21.setFlat(False)
        self.groupBox_21 = QGroupBox(self.groupBox_2)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(10, 220, 911, 61))
        self.groupBox_21.setFont(font2)
        self.lineEdit8 = QLineEdit(self.groupBox_21)
        self.lineEdit8.setObjectName(u"lineEdit8")
        self.lineEdit8.setEnabled(False)
        self.lineEdit8.setGeometry(QRect(10, 20, 691, 20))
        self.pushButton10 = QPushButton(self.groupBox_21)
        self.pushButton10.setObjectName(u"pushButton10")
        self.pushButton10.setGeometry(QRect(810, 20, 93, 28))
        self.pushButton22 = QPushButton(self.groupBox_21)
        self.pushButton22.setObjectName(u"pushButton22")
        self.pushButton22.setGeometry(QRect(710, 20, 93, 28))
        self.pushButton22.setFont(font2)
        self.pushButton22.setAutoDefault(False)
        self.pushButton22.setFlat(False)
        self.groupBox_23 = QGroupBox(self.groupBox_2)
        self.groupBox_23.setObjectName(u"groupBox_23")
        self.groupBox_23.setGeometry(QRect(10, 290, 911, 61))
        self.groupBox_23.setFont(font2)
        self.lineEdit9 = QLineEdit(self.groupBox_23)
        self.lineEdit9.setObjectName(u"lineEdit9")
        self.lineEdit9.setEnabled(False)
        self.lineEdit9.setGeometry(QRect(10, 20, 591, 20))
        self.pushButton11 = QPushButton(self.groupBox_23)
        self.pushButton11.setObjectName(u"pushButton11")
        self.pushButton11.setGeometry(QRect(710, 20, 93, 28))
        self.pushButton11.setFont(font1)
        self.pushButton12 = QPushButton(self.groupBox_23)
        self.pushButton12.setObjectName(u"pushButton12")
        self.pushButton12.setGeometry(QRect(810, 20, 93, 28))
        self.pushButton12.setFont(font1)
        self.pushButton23 = QPushButton(self.groupBox_23)
        self.pushButton23.setObjectName(u"pushButton23")
        self.pushButton23.setGeometry(QRect(610, 20, 93, 28))
        self.pushButton23.setFont(font2)
        self.pushButton23.setAutoDefault(False)
        self.pushButton23.setFlat(False)
        self.groupBox_1 = QGroupBox(self.groupBox_2)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setGeometry(QRect(10, 80, 911, 61))
        palette3 = QPalette()
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.groupBox_1.setPalette(palette3)
        self.groupBox_1.setFont(font2)
        self.lineEdit5 = QLineEdit(self.groupBox_1)
        self.lineEdit5.setObjectName(u"lineEdit5")
        self.lineEdit5.setEnabled(False)
        self.lineEdit5.setGeometry(QRect(10, 20, 691, 20))
        self.lineEdit5.setFont(font2)
        self.pushButton6 = QPushButton(self.groupBox_1)
        self.pushButton6.setObjectName(u"pushButton6")
        self.pushButton6.setGeometry(QRect(810, 20, 93, 28))
        self.pushButton6.setFont(font2)
        self.pushButton6.setAutoDefault(False)
        self.pushButton6.setFlat(False)
        self.pushButton19 = QPushButton(self.groupBox_1)
        self.pushButton19.setObjectName(u"pushButton19")
        self.pushButton19.setGeometry(QRect(710, 20, 93, 28))
        self.pushButton19.setFont(font2)
        self.pushButton19.setAutoDefault(False)
        self.pushButton19.setFlat(False)
        self.groupBox = QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 20, 151, 51))
        self.groupBox.setFont(font2)
        self.comboBox4 = QComboBox(self.groupBox)
        self.comboBox4.setObjectName(u"comboBox4")
        self.comboBox4.setGeometry(QRect(10, 20, 131, 22))
        self.pushButton14 = QPushButton(self.groupBox_2)
        self.pushButton14.setObjectName(u"pushButton14")
        self.pushButton14.setGeometry(QRect(170, 20, 93, 51))
        self.pushButton14.setFont(font2)
        self.pushButton15 = QPushButton(self.groupBox_2)
        self.pushButton15.setObjectName(u"pushButton15")
        self.pushButton15.setGeometry(QRect(280, 20, 93, 51))
        self.pushButton15.setFont(font2)
        self.pushButton16 = QPushButton(self.groupBox_2)
        self.pushButton16.setObjectName(u"pushButton16")
        self.pushButton16.setGeometry(QRect(380, 20, 93, 51))
        self.pushButton16.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 951, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton3.setDefault(True)
        self.pushButton2.setDefault(True)
        self.pushButton21.setDefault(False)
        self.pushButton22.setDefault(False)
        self.pushButton11.setDefault(True)
        self.pushButton12.setDefault(True)
        self.pushButton23.setDefault(False)
        self.pushButton6.setDefault(False)
        self.pushButton19.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MIIL PARAMETER CREATER", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"STATE", None))
        self.pushButton3.setText(QCoreApplication.translate("MainWindow", u"SAVE SATE", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"LOAD STATE", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"CREATE PARAMETER FILE", None))
        self.groupBox_24.setTitle(QCoreApplication.translate("MainWindow", u"DATASET FOLDER", None))
        self.pushButton5.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.pushButton21.setText(QCoreApplication.translate("MainWindow", u"RESET", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("MainWindow", u"WEIGHTS FOLDER", None))
        self.pushButton10.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.pushButton22.setText(QCoreApplication.translate("MainWindow", u"RESET", None))
        self.groupBox_23.setTitle(QCoreApplication.translate("MainWindow", u"PARAMETER FILE", None))
        self.pushButton11.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.pushButton12.setText(QCoreApplication.translate("MainWindow", u"SAVE", None))
        self.pushButton23.setText(QCoreApplication.translate("MainWindow", u"RESET", None))
        self.groupBox_1.setTitle(QCoreApplication.translate("MainWindow", u"LABEL FILE", None))
        self.pushButton6.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.pushButton19.setText(QCoreApplication.translate("MainWindow", u"RESET", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"PERCENTAGE OF VALID", None))
        self.pushButton14.setText(QCoreApplication.translate("MainWindow", u"SHOW PRM", None))
        self.pushButton15.setText(QCoreApplication.translate("MainWindow", u"SHOW TRAIN", None))
        self.pushButton16.setText(QCoreApplication.translate("MainWindow", u"SHOW VALID", None))
    # retranslateUi

